version: "3.9"
services:
    elastic:
        image: elasticsearch:8.3.3
        container_name: es01
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - xpack.security.enrollment.enabled=false
            - ingest.geoip.downloader.enabled=false
            - "http.cors.enabled=true"
            - "http.cors.allow-origin=\"*\""
            - "http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE"
            - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length"
            - "http.cors.allow-credentials=true"
        volumes:
            - ./elastic_data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - elastic

    kibana:
        image: kibana:8.3.3
        container_name: kib01
        environment:
            - xpack.security.enabled=false
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        networks:
            - elastic

networks:
    elastic:
        name: elastic
        driver: bridge